.Dd December 8, 2022
.Dt elfgraph 1
.Sh NAME
.Nm elfgraph
.Nd visualize ELF file dependencies
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl T Ar format
.Op Ar
.Sh DESCRIPTION
.Nm
generates a graph of relationships between ELF files: executables and libraries.
It only considers the files that are passed as positional parameters, and does
not attempt to locate the missing files.

The files that are required but not found will be included in the output, but
grayed out.

.Nm
can render the graph by itself (the default), or print the graph in textual form
for further processing by dot (see the
.Fl T
option)

The options are as follows:
.Bl -tag -width Ds
.It Fl h
Display help.

.It Fl T
Output type. Two output formats are supported:
.Cm tk
(default) and
.Cm dot .

The
.Cm tk
output type creates a window a displays the graph.

The
.Cm dot
output type prints the graph in dot format to stdout.

.El
